ru:
  locale: ru-RU
  languageName: Русский
  contentDir: content/ru
  weight: 1
  title: Гольцов Вячеслав
  params:
    description: Персональный академический сайт

en:
  locale: en-US
  languageName: English
  contentDir: content/en
  weight: 2
  title: Viacheslav Goltsov
  params:
    description: Personal academic website
