ru:
  locale: ru-RU
  label: Русский
  contentDir: content/ru
  weight: 1
  title: Гольцов Вячеслав
  params:
    description: Персональный академический сайт

en:
  locale: en-US
  label: English
  contentDir: content/en
  weight: 2
  title: Viacheslav Goltsov
  params:
    description: Personal academic website
