# Русский язык (основной)
ru:
  locale: ru-RU
  languageName: Русский
  weight: 1
  title: Гольцов Вячеслав
  params:
    description: Персональный академический сайт

# Английский язык
en:
  locale: en-US
  languageName: English
  weight: 2
  title: Viacheslav Goltsov
  params:
    description: Personal academic website
